"""Initial migration with all models

Revision ID: 9f1bcb925634
Revises: 
Create Date: 2025-11-24 15:14:38.695013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f1bcb925634'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('default_style', sa.Integer(), nullable=True),
    sa.Column('default_bias', sa.Float(), nullable=True),
    sa.Column('default_stroke_color', sa.String(length=20), nullable=True),
    sa.Column('default_stroke_width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('character_override_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('page_size_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_size_presets_name'), 'page_size_presets', ['name'], unique=True)
    op.create_table('usage_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('svg_generations', sa.Integer(), nullable=True),
    sa.Column('batch_generations', sa.Integer(), nullable=True),
    sa.Column('total_lines_generated', sa.Integer(), nullable=True),
    sa.Column('total_characters_generated', sa.Integer(), nullable=True),
    sa.Column('total_processing_time', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='_user_date_uc')
    )
    op.create_index(op.f('ix_usage_statistics_date'), 'usage_statistics', ['date'], unique=False)
    op.create_index(op.f('ix_usage_statistics_user_id'), 'usage_statistics', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_activities_timestamp'), 'user_activities', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_activities_user_id'), 'user_activities', ['user_id'], unique=False)
    op.create_table('character_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(length=1), nullable=False),
    sa.Column('svg_data', sa.Text(), nullable=False),
    sa.Column('viewbox_x', sa.Float(), nullable=True),
    sa.Column('viewbox_y', sa.Float(), nullable=True),
    sa.Column('viewbox_width', sa.Float(), nullable=False),
    sa.Column('viewbox_height', sa.Float(), nullable=False),
    sa.Column('baseline_offset', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['character_override_collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collection_character', 'character_overrides', ['collection_id', 'character'], unique=False)
    op.create_index(op.f('ix_character_overrides_character'), 'character_overrides', ['character'], unique=False)
    op.create_index(op.f('ix_character_overrides_collection_id'), 'character_overrides', ['collection_id'], unique=False)
    op.create_table('template_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('page_size_preset_id', sa.Integer(), nullable=False),
    sa.Column('orientation', sa.String(length=20), nullable=False),
    sa.Column('margin_top', sa.Float(), nullable=True),
    sa.Column('margin_right', sa.Float(), nullable=True),
    sa.Column('margin_bottom', sa.Float(), nullable=True),
    sa.Column('margin_left', sa.Float(), nullable=True),
    sa.Column('margin_unit', sa.String(length=10), nullable=False),
    sa.Column('line_height', sa.Float(), nullable=True),
    sa.Column('line_height_unit', sa.String(length=10), nullable=True),
    sa.Column('empty_line_spacing', sa.Float(), nullable=True),
    sa.Column('text_alignment', sa.String(length=20), nullable=False),
    sa.Column('global_scale', sa.Float(), nullable=True),
    sa.Column('auto_size', sa.Boolean(), nullable=True),
    sa.Column('manual_size_scale', sa.Float(), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('biases', sa.Text(), nullable=True),
    sa.Column('per_line_styles', sa.Text(), nullable=True),
    sa.Column('stroke_colors', sa.Text(), nullable=True),
    sa.Column('stroke_widths', sa.Text(), nullable=True),
    sa.Column('horizontal_stretch', sa.Float(), nullable=True),
    sa.Column('denoise', sa.Boolean(), nullable=True),
    sa.Column('character_width', sa.Float(), nullable=True),
    sa.Column('wrap_ratio', sa.Float(), nullable=True),
    sa.Column('wrap_utilization', sa.Float(), nullable=True),
    sa.Column('use_chunked_generation', sa.Boolean(), nullable=True),
    sa.Column('adaptive_chunking', sa.Boolean(), nullable=True),
    sa.Column('adaptive_strategy', sa.String(length=50), nullable=True),
    sa.Column('words_per_chunk', sa.Integer(), nullable=True),
    sa.Column('chunk_spacing', sa.Float(), nullable=True),
    sa.Column('max_line_width', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['page_size_preset_id'], ['page_size_presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_presets_name'), 'template_presets', ['name'], unique=True)
    op.create_index(op.f('ix_template_presets_page_size_preset_id'), 'template_presets', ['page_size_preset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_presets_page_size_preset_id'), table_name='template_presets')
    op.drop_index(op.f('ix_template_presets_name'), table_name='template_presets')
    op.drop_table('template_presets')
    op.drop_index(op.f('ix_character_overrides_collection_id'), table_name='character_overrides')
    op.drop_index(op.f('ix_character_overrides_character'), table_name='character_overrides')
    op.drop_index('idx_collection_character', table_name='character_overrides')
    op.drop_table('character_overrides')
    op.drop_index(op.f('ix_user_activities_user_id'), table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_timestamp'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_usage_statistics_user_id'), table_name='usage_statistics')
    op.drop_index(op.f('ix_usage_statistics_date'), table_name='usage_statistics')
    op.drop_table('usage_statistics')
    op.drop_index(op.f('ix_page_size_presets_name'), table_name='page_size_presets')
    op.drop_table('page_size_presets')
    op.drop_table('character_override_collections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
