"""Add BatchJob model and User.email field

Revision ID: 8f06fbc5994c
Revises:
Create Date: 2026-01-12 17:26:46.241124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8f06fbc5994c'
down_revision = None
branch_labels = None
depends_on = None


def table_exists(table_name):
    """Check if a table exists in the database."""
    bind = op.get_bind()
    inspector = inspect(bind)
    return table_name in inspector.get_table_names()


def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create batch_jobs table only if it doesn't exist
    if not table_exists('batch_jobs'):
        op.create_table('batch_jobs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=False),
        sa.Column('is_private', sa.Boolean(), nullable=False),
        sa.Column('scheduled_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('input_file_path', sa.String(length=500), nullable=True),
        sa.Column('output_file_path', sa.String(length=500), nullable=True),
        sa.Column('row_count', sa.Integer(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('error_count', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('processing_log', sa.Text(), nullable=True),
        sa.Column('celery_task_id', sa.String(length=100), nullable=True),
        sa.Column('parameters', sa.Text(), nullable=True),
        sa.Column('email_notification_sent', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_batch_jobs_celery_task_id'), ['celery_task_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_batch_jobs_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_batch_jobs_priority'), ['priority'], unique=False)
            batch_op.create_index(batch_op.f('ix_batch_jobs_scheduled_at'), ['scheduled_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_batch_jobs_status'), ['status'], unique=False)
            batch_op.create_index(batch_op.f('ix_batch_jobs_user_id'), ['user_id'], unique=False)

    # Add email column to users table only if it doesn't exist
    if not column_exists('users', 'email'):
        # Step 1: Add column as nullable first
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))

        # Step 2: Update existing users with placeholder emails based on their username
        connection = op.get_bind()
        connection.execute(sa.text(
            "UPDATE users SET email = username || '@placeholder.local' WHERE email IS NULL"
        ))

        # Step 3: Now make the column non-nullable and add unique constraint with a name
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('email', nullable=False)
            batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('users', 'email'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.drop_constraint('uq_users_email', type_='unique')
            batch_op.drop_column('email')

    if table_exists('batch_jobs'):
        with op.batch_alter_table('batch_jobs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_batch_jobs_user_id'))
            batch_op.drop_index(batch_op.f('ix_batch_jobs_status'))
            batch_op.drop_index(batch_op.f('ix_batch_jobs_scheduled_at'))
            batch_op.drop_index(batch_op.f('ix_batch_jobs_priority'))
            batch_op.drop_index(batch_op.f('ix_batch_jobs_created_at'))
            batch_op.drop_index(batch_op.f('ix_batch_jobs_celery_task_id'))

        op.drop_table('batch_jobs')
    # ### end Alembic commands ###
